services:
  # Banco de Dados
  postgres:
    image: postgres:16
    container_name: postgres-votacao
    environment:
      POSTGRES_DB: votacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - votacao-network

  # Mensageria
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-votacao
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - votacao-network

  # Cache
  redis:
    image: redis:7-alpine
    container_name: votacao-redis
    ports:
      - "6379:6379"
    networks:
      - votacao-network

networks:
  votacao-network:
    driver: bridge

volumes:
  postgres_data:
